2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_setup.py:_flush():69] setting env: {}
2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_init.py:_log_setup():336] Logging user logs to /home/georgenakayama/CS229_DeepCubeA/wandb/run-20210430_055010-cube3_layer3-cube3layer3_random_data_gen/logs/debug.log
2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_init.py:_log_setup():337] Logging internal logs to /home/georgenakayama/CS229_DeepCubeA/wandb/run-20210430_055010-cube3_layer3-cube3layer3_random_data_gen/logs/debug-internal.log
2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_init.py:init():369] calling init triggers
2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'env': 'cube3_layer3', 'debug': False, 'lr': 0.001, 'lr_d': 0.9999993, 'max_itrs': 1000000, 'batch_size': 1000, 'single_gpu_training': True, 'loss_thresh': 0.2, 'states_per_update': 500000, 'epochs_per_update': 1, 'num_update_procs': 30, 'update_nnet_batch_size': 10000, 'max_update_steps': 1, 'update_method': 'GBFS', 'eps_max': 0, 'num_test': 10000, 'back_max': 30, 'dynamic_back_max': False, 'dynamic_back_max_per': 25, 'fixed_difficulty': False, 'uniform_data_gen': True, 'nnet_name': 'cube3layer3_random_data_gen', 'update_num': 0, 'save_dir': 'saved_models', 'targ_dir': 'saved_models/cube3layer3_random_data_gen//target/', 'curr_dir': 'saved_models/cube3layer3_random_data_gen//current/', 'output_save_loc': 'saved_models/cube3layer3_random_data_gen//output.txt'}
2021-04-30 05:50:10,982 INFO    MainThread:11547 [wandb_init.py:init():418] starting backend
2021-04-30 05:50:10,982 INFO    MainThread:11547 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-30 05:50:10,999 INFO    MainThread:11547 [backend.py:ensure_launched():123] starting backend process...
2021-04-30 05:50:11,016 INFO    MainThread:11547 [backend.py:ensure_launched():128] started backend process with pid: 11572
2021-04-30 05:50:11,024 INFO    MainThread:11547 [wandb_init.py:init():423] backend started and connected
2021-04-30 05:50:11,028 INFO    MainThread:11547 [wandb_init.py:init():465] updated telemetry
2021-04-30 05:50:11,035 INFO    MainThread:11547 [wandb_init.py:init():484] communicating current version
2021-04-30 05:50:11,967 INFO    MainThread:11547 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.28 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-30 05:50:11,967 INFO    MainThread:11547 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-30 05:50:12,120 INFO    MainThread:11547 [wandb_init.py:init():522] starting run threads in backend
2021-04-30 05:50:17,130 INFO    MainThread:11547 [wandb_run.py:_console_start():1524] atexit reg
2021-04-30 05:50:17,130 INFO    MainThread:11547 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-30 05:50:17,130 INFO    MainThread:11547 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-30 05:50:17,133 INFO    MainThread:11547 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-30 05:50:17,133 INFO    MainThread:11547 [wandb_init.py:init():546] run started, returning control to user process
2021-04-30 05:58:40,824 INFO    MainThread:11547 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-30 05:58:40,824 INFO    MainThread:11547 [wandb_run.py:_restore():1466] restore
2021-04-30 05:58:43,001 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1132
  total_bytes: 1132
}

2021-04-30 05:58:43,541 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1132
  total_bytes: 8567
}

2021-04-30 05:58:43,852 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1132
  total_bytes: 8567
}

2021-04-30 05:58:43,955 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8567
  total_bytes: 8567
}

2021-04-30 05:58:44,057 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8567
  total_bytes: 8567
}

2021-04-30 05:58:44,159 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8567
  total_bytes: 8567
}

2021-04-30 05:58:44,261 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8567
  total_bytes: 8567
}

2021-04-30 05:58:44,363 INFO    MainThread:11547 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8567
  total_bytes: 8567
}

2021-04-30 05:58:45,833 INFO    MainThread:11547 [wandb_run.py:_show_summary():1771] rendering summary
2021-04-30 05:58:45,833 INFO    MainThread:11547 [wandb_run.py:_show_files():1838] logging synced files
